// This file has been autogenerated from a class added in the UI designer.

using System;
using SQLite;
using Foundation;
using UIKit;

namespace Demo
{
	public partial class AddViewController : UIViewController
	{
        public static int db_int;
		public AddViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            AddToDB.TouchDown += AddToDB_TouchDown;
            //Add();
        }

        private void AddToDB_TouchDown(object sender, EventArgs e)
        {

            Add();
        }

        public void Add()
        {
            BudgetInfo budget = new BudgetInfo
            {
                m_Reason = Reason.Text,
                m_spent = float.Parse(Cost.Text),
                m_Date = RemoveSpaces(Date.Date.ToString()),
                userId = db_int
            };
            using(SQLiteConnection conn = new SQLiteConnection(AppDelegate.FilePath))
            {
                conn.Insert(budget);
            }
        }
        private string RemoveSpaces(string date)
        {
            string[] datea = date.Split(" ");
            return datea[0];

        }

    }
}
