// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Demo
{
	public partial class AddViewController : UIViewController
	{
        public static int db_int;
		public AddViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            AddToDB();
        }
        public void AddToDB()
        {
            BudgetInfo budget = new BudgetInfo
            {
                m_Reason = Reason.Text,
                m_spent = float.Parse(Cost.Text),
                m_Date = RemoveSpaces(Date.Date.ToString()),
                userId = db_int
            };
        }
        private string RemoveSpaces(string date)
        {
            string[] datea = date.Split(" ");
            return datea[0];

        }

    }
}
