// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Demo
{
	public partial class AddViewController : UIViewController
	{
		public AddViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
