// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Demo
{
	public partial class CreateViewController : UIViewController
	{
		public CreateViewController (IntPtr handle) : base (handle)
		{
        }
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            //View.BackgroundColor = UIColor.Gray;
        }
    }
}
