// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Demo
{
	public partial class ShowSpent : UITableViewCell
	{
		public ShowSpent (IntPtr handle) : base (handle)
		{
		}
	}
}
