// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using SQLite;
using Foundation;
using UIKit;

namespace Demo
{
	public partial class TrackerViewController : UIViewController
	{
        List<Person> user = new List<Person>();
        List<BudgetInfo> Info = new List<BudgetInfo>();
        public static int db_int;
        public TrackerViewController (IntPtr handle) : base (handle)
		{
		}
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            Title = "Tracker";
            
            ConnectToDB();
            TrackerName.Text += user[ExistingViewController.db_int].m_Name;

            UITableView _Budget;
            _Budget = new UITableView
            {
                Frame = new CoreGraphics.CGRect(0, 100, View.Bounds.Width, View.Bounds.Height),
                Source = new ListSpent(Info)
            };

            View.AddSubview(_Budget);

            AddToBudget.TouchDown += AddToBudget_TouchDown;
            ShowMoney();

            configure();

        }

        private void AddToBudget_TouchDown(object sender, EventArgs e)
        {
            AddViewController tracker = Storyboard.InstantiateViewController(identifier: "AddViewController") as AddViewController;
            AddViewController.db_int = db_int;
            NavigationController.PushViewController(tracker, true);
        }

        private void configure()
        {
            
        }

        private void ShowMoney()
        {

        }

        private void ConnectToDB()
        {
            using (SQLiteConnection conn1 = new SQLiteConnection(AppDelegate.FilePath))
            {
                Info = conn1.Table<BudgetInfo>().ToList();
            }
            //using (SQLiteConnection conn = new SQLiteConnection(AppDelegate.FilePath))
            //{
            //    Info = conn.Table<BudgetInfo>().ToList();
            //}
        }
    }
}
